#!/usr/bin/swift

import Foundation

// Firebase used to be generated here too; it's migrated to Resources/services.json
// (see Scripts/generators/Sources/UpdateServicesJSON/Generators/FirebaseGenerator.swift).

struct GCPService {
    let serviceName: String
    let dashboardName: String

    init(dashboardName: String) {
        self.dashboardName = dashboardName

        if !dashboardName.hasPrefix("Google") {
            serviceName = "Google \(dashboardName)"
        } else {
            serviceName = dashboardName
        }
    }

    var className: String {
        var sanitizedName = serviceName
        sanitizedName = sanitizedName.replacingOccurrences(of: " & ", with: "And")
        sanitizedName = sanitizedName.replacingOccurrences(of: "/", with: "")
        sanitizedName = sanitizedName.replacingOccurrences(of: ":", with: "")
        sanitizedName = sanitizedName.replacingOccurrences(of: "-", with: "")
        sanitizedName = sanitizedName.replacingOccurrences(of: "(", with: "")
        sanitizedName = sanitizedName.replacingOccurrences(of: ")", with: "")
        return sanitizedName.components(separatedBy: " ")
            .map { $0.capitalized(firstLetterOnly: true) }
            .joined(separator: "")
    }

    var output: String {
        return """
        final class \(className): GoogleCloudPlatform, SubService {
            let name = "\(serviceName)"
            let dashboardName = "\(dashboardName)"
        }
        """
    }
}

extension String {
    subscript(_ range: NSRange) -> String {
        // Why we still have to do this shit in 2019 I don't know
        let start = self.index(self.startIndex, offsetBy: range.lowerBound)
        let end = self.index(self.startIndex, offsetBy: range.upperBound)
        let subString = self[start..<end]
        return String(subString)
    }

    func capitalized(firstLetterOnly: Bool) -> String {
        return firstLetterOnly ? (prefix(1).capitalized + dropFirst()) : self
    }
}

func envVariable(forKey key: String) -> String {
    guard let variable = ProcessInfo.processInfo.environment[key] else {
        print("error: Environment variable '\(key)' not set")
        exit(1)
    }

    return variable
}

func discoverServices() -> [GCPService] {
    var result = [GCPService]()

    var dataResult: Data?

    let semaphore = DispatchSemaphore(value: 0)
    URLSession.shared.dataTask(with: URL(string: "https://status.cloud.google.com")!) { data, _, _ in
        dataResult = data
        semaphore.signal()
    }.resume()

    _ = semaphore.wait(timeout: .now() + .seconds(10))

    guard let data = dataResult, var body = String(data: data, encoding: .utf8) else {
        print("warning: Build script generate_google_services could not retrieve list of GCP services")
        exit(0)
    }

    body = body.replacingOccurrences(of: "\n", with: "")

    // swiftlint:disable:next force_try
    let regex = try! NSRegularExpression(
        pattern: "__product\" scope=\"row\">[\\s\\n]*(.+?)[\\s\\n]*<.*?\\/th>",
        options: [.caseInsensitive, .dotMatchesLineSeparators]
    )

    let range = NSRange(location: 0, length: body.count)
    regex.enumerateMatches(in: body, options: [], range: range) { textCheckingResult, _, _ in
        guard let textCheckingResult = textCheckingResult, textCheckingResult.numberOfRanges == 2 else { return }

        let dashboardName = body[textCheckingResult.range(at: 1)]
        result.append(GCPService(dashboardName: dashboardName))
    }

    return result
}

func main() {
    let srcRoot = envVariable(forKey: "SRCROOT")
    let outputPath = "\(srcRoot)/stts/Services/Generated/GoogleCloudPlatformServices.swift"
    let services = discoverServices()

    let header = """
    // This file is generated by generate_google_services.swift and should not be modified manually.
    // swiftlint:disable superfluous_disable_command type_name

    import Foundation

    """

    let content = services.map { $0.output }.joined(separator: "\n\n")
    let footer = ""

    let output = [header, content, footer].joined(separator: "\n")

    // swiftlint:disable:next force_try
    try! output.write(toFile: outputPath, atomically: true, encoding: .utf8)

    print("Finished generating Google Cloud Platform services.")
}

main()
